- hosts: ec2
  gather_facts: no      
  become: yes
  tasks:
    - name: Garantir que o Python 3 está instalado (bootstrapping)
      raw: |
        if ! command -v python3 &> /dev/null; then
          sudo yum install -y python3
        fi
      changed_when: false

    - name: Instalar pacotes básicos
      yum:
        name: [python3, python3-pip]
        state: present

    - name: Instalar bibliotecas Python
      pip:
        name: [boto3, pandas]

    - name: Criar diretórios de dados
      file:
        path: "/data/{{ item }}"
        state: directory
      loop:
        - raw
        - trusted
        - client
