name: Sprint5 Full Automation

on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Apply
        run: |
          sudo apt update -y
          sudo apt install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update -y
          sudo apt install -y terraform
          cd infra
          terraform init
          terraform apply -auto-approve
      - name: Configurar EC2 com Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAVE_PEM }}" > ~/.ssh/control-node-sprint5.pem
          chmod 400 ~/.ssh/control-node-sprint5.pem
          cd ansible
          ansible-playbook -i inventory setup.yml
      - name: Executar pipeline de dados
        run: |
          python -m pip install pandas
          python -m pip install boto3
          python scripts/data_pipeline.py
